[exector]
c = "cd $dir && gcc $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt"
cpp = "cd $dir && g++ $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt"
rust = "cargo run"
objective-c = "cd $dir && gcc -framework Cocoa $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt"
python = "python3 -u"
java = "cd $dir && javac $fileName && java $fileNameWithoutExt"
markdown = 'echo "hello"' 

[extention]
v = "cd $dir && iverilog sim$fileName $fileName && ./a.out"
